language: node_js
node_js:
 - "stable"
services:
 - postgresql

env:
 - SECRET=secrett  

before_script:
 - psql -c 'create database book_a_meal;' -U postgres
 - psql -c "CREATE USER adekunleoluwafemi WITH PASSWORD 'phemonick';" -U postgres
script:
 - npm test

after_success: npm run coverage