language: node_js
node_js: 
  - "stable"
  services:
 - postgresql
env:
 - JWT_SECRET=secrett

before_script:
 - psql -c 'create database book-a-meal;' -U postgres
 - psql -c "CREATE USER femi WITH PASSWORD 'fem';" -U postgres
 - npm install -g codecov
  
script: 
      - npm install && npm test
after_success:
  - npm run coverage