language: node_js
node_js:
 - "stable"
services:
 - postgresql

env:
 - SECRET=secrett  

before_install:
 - npm i -g node-gyp node-pre-gyp
 - npm i -g codecov

before_script:
 - psql -c 'create database book_a_meal;' -U postgres
 - psql -c "CREATE USER adekunleoluwafemi WITH PASSWORD 'phemonick';" -U postgres
 
script:
 - npm run test:client
 - npm test

after_success: 
 - npm run coverage
 - codecov
